language: c
install: 
  - sudo apt-get install libsdl1.2-dev
  - sudo apt-get install libsdl-image1.2-dev
  - sudo apt-get install libsdl-mixer1.2-dev
  - sudo apt-get install libsdl-ttf2.0-dev
  - sudo apt-get install libsdl-gfx1.2-dev
  - sudo apt-get install libimlib2
  - sudo apt-get install libimlib2-dev 
compiler:
  - gcc
  - clang
script: 
  - ./bootstrap
  - make
  - make install
