language: c
install: 
  - sudo apt-get install libsdl1.2debian
  - sudo apt-get install libsdl1.2-dev
  - sudo apt-get install libsdl-image1.2
  - sudo apt-get install libsdl-image1.2-dev
  - sudo apt-get install libsdl-mixer1.2-dev
  - sudo apt-get install libsdl-ttf2.0-dev
  - sudo apt-get install libsdl-gfx1.2-dev
  - chmod +x bootstrap
compiler: clang
script: 
  - ./bootstrap
  - ./configure	
  - make
  - pwd
  - ls
  - ls src
  - cd src
  - ./pwntcha ../testsuite/xanga/xanga_000.jpeg
  - ./pwntcha ../testsuite/xanga/xanga_001.jpeg
  - ./pwntcha ../testsuite/authimage/authimage_000.jpeg
  - ./pwntcha ../testsuite/authimage/authimage_001.jpeg
  - ./pwntcha ../testsuite/paypal/paypal_000.jpeg
  - ./pwntcha ../testsuite/paypal/paypal_001.jpeg
  - ./pwntcha ../testsuite/xanga2/xanga_000.jpeg
  - ./pwntcha ../testsuite/xanga2/xanga_001.jpeg